package handlers

import (
	"gopkg.in/telebot.v4"

	"github.com/DKhorkov/plantsCareTelegramBot/internal/buttons"
	"github.com/DKhorkov/plantsCareTelegramBot/internal/interfaces"
)

var Default = map[any]interfaces.Handler{
	"/start":                                   Start,
	"/help":                                    Help,
	&buttons.CreateGroup:                       AddGroupCallback,
	&buttons.ManageGroups:                      ManageGroupsCallback,
	&buttons.CreatePlant:                       AddPlantCallback,
	&buttons.ManagePlants:                      ManagePlantsCallback,
	&buttons.BackToStart:                       BackToMenu,
	&buttons.BackToAddGroupTitle:               AddGroupCallback,
	&buttons.BackToAddGroupDescription:         BackToAddGroupDescriptionCallback,
	&buttons.SkipGroupDescription:              SkipGroupDescriptionCallback,
	&buttons.BackToAddGroupLastWateringDate:    BackToAddGroupLastWateringDateCallback,
	&buttons.BackToAddGroupWateringInterval:    BackToAddGroupWateringIntervalCallback,
	&buttons.ConfirmAddGroup:                   ConfirmAddGroupCallback,
	&buttons.Menu:                              BackToMenu,
	&buttons.BackToAddPlantTitle:               AddPlantCallback,
	&buttons.BackToAddPlantDescription:         BackToAddPlantDescriptionCallback,
	&buttons.SkipPlantDescription:              SkipPlantDescriptionCallback,
	&buttons.BackToAddPlantGroup:               BackToAddPlantGroupCallback,
	&buttons.AcceptAddPlantPhoto:               AcceptAddPlantPhotoCallback,
	&buttons.RejectAddPlantPhoto:               RejectAddPlantPhotoCallback,
	&buttons.BackToAddPlantPhotoQuestion:       BackToAddPlantPhotoQuestionCallback,
	&buttons.ConfirmAddPlant:                   ConfirmAddPlantCallback,
	&buttons.BackToAddPlantPhoto:               AcceptAddPlantPhotoCallback,
	&buttons.CreateAnotherPlant:                AddPlantCallback,
	&buttons.BackToManagePlantsChooseGroup:     ManagePlantsCallback,
	&buttons.BackToManagePlant:                 BackToManagePlantCallback,
	&buttons.ManagePlantChange:                 ManagePlantChangeCallback,
	&buttons.ManagePlantRemoval:                ManagePlantRemovalCallback,
	&buttons.ConfirmPlantRemoval:               ConfirmPlantRemovalCallback,
	&buttons.BackToManagePlantAction:           BackToManagePlantActionCallback,
	&buttons.ManagePlantChangeTitle:            ManagePlantChangeTitleCallback,
	&buttons.ManagePlantChangeDescription:      ManagePlantChangeDescriptionCallback,
	&buttons.ManagePlantChangeGroup:            ManagePlantChangeGroupCallback,
	&buttons.ManagePlantChangePhoto:            ManagePlantChangePhotoCallback,
	&buttons.BackToManagePlantChange:           ManagePlantChangeCallback,
	&buttons.BackToManageGroup:                 ManageGroupsCallback,
	&buttons.ManageGroupSeePlants:              ManageGroupSeePlantsCallback,
	&buttons.ManageGroupChange:                 ManageGroupChangeCallback,
	&buttons.ManageGroupRemoval:                ManageGroupRemovalCallback,
	&buttons.ConfirmGroupRemoval:               ConfirmGroupRemovalCallback,
	&buttons.BackToManageGroupAction:           BackToManageGroupActionCallback,
	&buttons.BackToManageGroupChange:           ManageGroupChangeCallback,
	&buttons.ManageGroupChangeTitle:            ManageGroupChangeTitleCallback,
	&buttons.ManageGroupChangeDescription:      ManageGroupChangeDescriptionCallback,
	&buttons.ManageGroupChangeLastWateringDate: ManageGroupChangeLastWateringDateCallback,
	&buttons.ManageGroupChangeWateringInterval: ManageGroupChangeWateringIntervalCallback,
	telebot.OnText:                             OnText,
	telebot.OnPhoto:                            OnPhoto,
	telebot.OnMedia:                            OnMedia,
	telebot.OnAudio:                            Delete,
	telebot.OnAnimation:                        Delete,
	telebot.OnBoost:                            Delete,
	telebot.OnContact:                          Delete,
	telebot.OnDice:                             Delete,
	telebot.OnPoll:                             Delete,
	telebot.OnDocument:                         Delete,
	telebot.OnLocation:                         Delete,
}
